
trigger: none

pool:
  name: Local Agents

variables:
- group: cs2-release-vars

steps:
- checkout: self

- bash: |
    sudo adduser $(USER_NAME)
    sudo adduser $(USER_NAME) sudo
  displayName: 'Create New User'

- bash: |
    sudo ufw allow from any to any port $(SERVER_PORT) proto tcp
    sudo ufw allow from any to any port $(SERVER_PORT) proto udp
  displayName: 'Configure Firewall'

- bash: |
    sudo cp -r /home/$(USER_NAME)/$(INSTALL_DIR)/game/csgo/logs/* /home/$(USER_NAME)/bizzylogs/
  displayName: 'Copy Logs'
  continueOnError: true

- bash: |
    sudo cp $(Build.SourcesDirectory)/src2ds1 /etc/init.d/src2ds1
    sudo chmod +x /etc/init.d/src2ds1
  displayName: 'Copy over src2ds1'
  continueOnError: true

- bash: |
    sudo /etc/init.d/src2ds1 stop
  displayName: 'Stop CS2 Server'

- bash: |
    sudo rm -rf /home/$(USER_NAME)/$(INSTALL_DIR)
  displayName: 'Delete CS2'

- task: replacetokens@5
  inputs:
    targetFiles: '**/*.cfg'
    encoding: 'auto'
    tokenPattern: 'default'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    actionOnNoFiles: 'continue'
    enableTransforms: false
    enableRecursion: false
    useLegacyPattern: false
    enableTelemetry: true

- bash: |
    cd /home/$(USER_NAME)
    sudo apt update
    sudo dpkg --add-architecture i386
    sudo apt-get upgrade
    sudo apt-get install libc6:i386 lib32z1 screen
    wget $(STEAMCMD_LOC)
    tar -xvzf steamcmd_linux.tar.gz --overwrite
    sudo rm steamcmd_linux.tar.gz 
    ./steamcmd.sh
    force_install_dir ./$(INSTALL_DIR)
    login anonymous
    app_update 730 validate
    quit
  displayName: 'Install SteamCMD and CS2'

- bash: |
    cd /home/$(USER_NAME)/$(INSTALL_DIR)/game/csgo/cfg
    sudo cp $(Build.SourcesDirectory)/server.cfg server.cfg --force
  displayName: 'Copy server.cfg'

- bash: |
    /etc/init.d/srcds1 start
  displayName: 'Start the Server'

