trigger: none

pool:
  name: Local Agents

variables:
- group: cs2-release-vars

steps:
- checkout: self

- task: SSH@0
  displayName: 'Create New User via SSH'
  inputs:
    sshEndpoint: 'bizzycs'
    runOptions: 'inline'
    inline: |
      if ! id "$(USER_NAME)" &>/dev/null; then
        sudo adduser $(USER_NAME)
        sudo adduser $(USER_NAME) sudo
      fi

- task: SSH@0
  displayName: 'Configure Firewall via SSH'
  inputs:
    sshEndpoint: 'bizzycs'
    runOptions: 'inline'
    inline: |
      sudo ufw allow from any to any port $(SERVER_PORT) proto tcp
      sudo ufw allow from any to any port $(SERVER_PORT) proto udp

- task: replacetokens@5
  inputs:
    targetFiles: |
      **/*.cfg
      src2ds1
    encoding: 'auto'
    tokenPattern: 'default'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    actionOnNoFiles: 'continue'
    enableTransforms: false
    enableRecursion: false
    useLegacyPattern: false
    enableTelemetry: true
  displayName: "Replace tokens"

- task: SSH@0
  displayName: 'Copy Logs via SSH'
  inputs:
    sshEndpoint: 'bizzycs'
    runOptions: 'inline'
    inline: |
      sudo cp -r /home/$(USER_NAME)/$(INSTALL_DIR)/game/csgo/logs/* /home/$(USER_NAME)/bizzylogs/ || true

- task: SSH@0
  displayName: 'Copy over src2ds1 via SSH'
  inputs:
    sshEndpoint: 'bizzycs'
    runOptions: 'inline'
    inline: |
      sudo cp $(Build.SourcesDirectory)/src2ds1 /etc/init.d/src2ds1
      sudo chmod +x /etc/init.d/src2ds1

- task: SSH@0
  displayName: 'Stop CS2 Server via SSH'
  inputs:
    sshEndpoint: 'bizzycs'
    runOptions: 'inline'
    inline: |
      sudo /etc/init.d/src2ds1 stop

- task: SSH@0
  displayName: 'Delete CS2 via SSH'
  inputs:
    sshEndpoint: 'bizzycs'
    runOptions: 'inline'
    inline: |
      sudo rm -rf /home/$(USER_NAME)/$(INSTALL_DIR)

- task: SSH@0
  displayName: 'Install SteamCMD and CS2 via SSH'
  inputs:
    sshEndpoint: 'bizzycs'
    runOptions: 'inline'
    inline: |
      cd /home/$(USER_NAME)
      sudo apt update
      sudo dpkg --add-architecture i386
      sudo apt-get upgrade
      sudo apt-get install libc6:i386 lib32z1 screen
      wget $(STEAMCMD_LOC)
      tar -xvzf steamcmd_linux.tar.gz --overwrite
      sudo rm steamcmd_linux.tar.gz 
      ./steamcmd.sh
      force_install_dir ./$(INSTALL_DIR)
      login anonymous
      app_update 730 validate
      quit

- task: SSH@0
  displayName: 'Copy server.cfg via SSH'
  inputs:
    sshEndpoint: 'bizzycs'
    runOptions: 'inline'
    inline: |
      cd /home/$(USER_NAME)/$(INSTALL_DIR)/game/csgo/cfg
      sudo cp $(Build.SourcesDirectory)/server.cfg server.cfg --force

- task: SSH@0
  displayName: 'Update Permissions via SSH'
  inputs:
    sshEndpoint: 'bizzycs'
    runOptions: 'inline'
    inline: |
      sudo chmod -R 750 /home/$(USER_NAME)/$(INSTALL_DIR)

- task: SSH@0
  displayName: 'Start the Server via SSH'
  inputs:
    sshEndpoint: 'bizzycs'
    runOptions: 'inline'
    inline: |
      /etc/init.d/src2ds1 start